services:
  db:
    image: postgres:17.4-alpine
    restart: always
    environment:
      POSTGRES_DB: revisium-dev
      POSTGRES_USER: revisium
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 1s
      timeout: 1s
      retries: 5
  revisium:
    depends_on:
      db:
        condition: service_healthy
    image: revisium/revisium:latest
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: postgresql://revisium:password@db:5432/revisium-dev?schema=public
